/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mainContractSol from "./MainContract.sol";
export type { mainContractSol };
export type { CreateToken } from "./CreateToken";
