/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mainContractSol from "./MainContract.sol";
export { CreateToken__factory } from "./CreateToken__factory";
